spring.application.name=noticiarioOficial
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/apiSpringData
spring.datasource.username=postgres
spring.datasource.password=adminn

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false


spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/APIEscolaDuartina

jwt.secret=your-256-bit-secret-key-here-minimum-32-characters-long


server.port=8081
